# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3e07245e952923cc459b0ac833efae52fef80895ffe0c32ae8e465e709b6fbfea12006e148356040d3c65aaafaa3ea44923177cef63472893addf267afd46387

test:
  secret_key_base: 61dce5731259fa612334bc19e62c1f6ba4c15aa9db5544c57d546da7ce6f126669a8343360965e982c928c127eef42b25497a4961a8ada27276bd5620218249f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
